### ISSUE TITLE
Hello World | My World

### ISSUE THREAD

**Issue by Yezhuming** [Yezhuming/gitalk-comments#1]
https://yezhuming.github.io/2019/07/18/hello-world/ 

 Welcome to Hexo! This is your very first post. Check documentation for more info. If you get any problems when using Hexo, you can find the answer in troubleshooting or you can ask me on GitHub.

**Comment by Yezhuming** [comment]
Hello World!

**Comment by k0m0rebi** [comment]
闸总在吗

**Comment by AnOrdinaryMan** [comment]
0.0

**Comment by k0m0rebi** [comment]
啊啊啊啊

**Comment by k0m0rebi** [comment]
wdnmd(～￣▽￣)～

**Comment by AnOrdinaryMan** [comment]
1.1
